### ISSUE TITLE
Complete Kanban board for ROR group Project (Recipe App)

### ISSUE THREAD

**Issue by AdnanOlarmmi** [ouasamine/heaven-of-recipes#7]
# Group capstone: set up your Kanban board

## Learning objectives
- Use the Kanban board with filled-in tasks that have categories and time estimations to assign work in groups.

## Description

In this activity, my team prepared a Kanban board with a GitHub project. As this is the very first group project in our Microverse journey.
In order to copy the Kanban board quickly, we used a special script prepared for us.

### Project requirements

- Joined a Zoom call as team-mates. Only one person copied the board on behalf of the entire team but helped during the call.
- We created an empty repository for our group project.
- Followed the steps described in [curriculum-tools-copy-projects](https://github.com/microverseinc/curriculum-tools-copy-projects).
- Opened the GitHub project (Kanban board) in our team repo.
- Made sure that in the card titles we can see: `Student A`, and `Student B`.
- Made sure that each card starts with `[Xpt]` - that number indicates the number of `points` that shows how complex the task is. **1 point = 1 hour of work**.
- Our group includes two people - so, we removed all cards with `Student C` in the title._
- Decided who in the team is `Student A`, or `Student B`.
- Each of the team members assigned themselves to the correct cards. We then decided who will be the assignee for the cards marked as group tasks. All cards on our Kanban board have assignees.

## Link and notes

- [Here is the link to our GitHub project](https://github.com/users/ouasamine/projects/1).
- We are a group of two smart individuals Adnan Is-haq 🙃 @AdnanOlarmmi  and Amine ouassef  😃  @ouasamine.

## Work and submission mode

- We implemented the above requirements only in **one repository** in our group.

## Appreciation
- Thanks for the review 🙃

**Comment by thecodechaser** [comment]
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @ouasamine, and @AdnanOlarmmi👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️

- [ ] Please make sure the time estimate distributions should be fair - no single person should be doing all of the most time-consuming tasks, The number of assigned points should be equal (+/- 5 points) for each member as requested in the project's requirements. I can see one member has more tasks and more points, Please make sure to distribute that equally between all members.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by rloterh** [comment]
## Status: Approved :heavy_check_mark:

Hi Team,  

Your task is complete! 🍾🍾 Congratulations!  🎉💯🌟 

## Highlights 👍
- Fair distribution of tasks

Keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
